### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by janekolszak** [foomo/htpasswd#1]
Hi!
Nice package! Simple and easy.

Could you please add a license file? MIT would be awesome.

Thanks

**Comment by janhalfar** [comment]
Hi Jan,

that is nice to hear! How about LGPL - would that work for you?

Cheers,

Jan

**Comment by janekolszak** [comment]
I don't think LGPL works with GO. I can't dynamically link to your library.

**Comment by janhalfar** [comment]
I am not much of a license expert - what licenses would work for you?

**Comment by janekolszak** [comment]
Apache 2, MIT I guess. I can't comply with LGPL with GO code.

**Comment by janhalfar** [comment]
Have fun Jan!
